### ISSUE TITLE
[Help] To filter forwarded messages

### ISSUE THREAD

**Issue by T4eslenko** [khoben/telemirror#100]
Привет, спасибо за программу, она супер. Переписал, чтобы пересылались сообщения с заданными словами (вместо пропуска). Никак не могу сделать не точный поиск по словам. Как изменить код, чтобы поиск осуществлялся по неточному совпадению, например, искало все слова, в которых встречается "дом" (домик, домкрат и тп). И можно ли через одну строку задать неточный поиск по нескольким ключивым словам?

Еще видел, что в предыдущих релизах у тебя фильтр прикручивался к конкретному каналу. Можно ли вернуть данную опцию? А то для нескольких каналов с разными ключевыми словами надо будет запускать несколько версий программы.

Спасибо

**Comment by khoben** [comment]
Пересылка с заданными словами это почти тоже самое, что [`SkipWithKeywordsFilter`](https://github.com/khoben/telemirror/blob/7c0ce27677b9f4b1e4f4d6739601ec3afa30997f/telemirror/messagefilters/messagefilters.py#L442), но нужно сделать обратное условие. Если не найдено, то не пересылать:
```python
async def _process_message(
        self, message: EventMessage, event_type: Type[EventLike]
    ) -> Tuple[bool, EventMessage]:
        return self._lookup_regex.search(message.message) is not None, message
```

**Comment by khoben** [comment]
Для нечеткого поиска нужно убрать \\b ([`self.BOUNDARY_REGEX`](https://github.com/khoben/telemirror/blob/7c0ce27677b9f4b1e4f4d6739601ec3afa30997f/telemirror/messagefilters/messagefilters.py#L448)) из регулярного выражения.

**Comment by khoben** [comment]
> Еще видел, что в предыдущих релизах у тебя фильтр прикручивался к конкретному каналу. Можно ли вернуть данную опцию? А то для нескольких каналов с разными ключевыми словами надо будет запускать несколько версий программы.

Теперь фильтры прикручиваются к связке источник-целевой канал, не нужно запускать несколько версий.

**Comment by T4eslenko** [comment]
> Теперь фильтры прикручиваются к связке источник-целевой канал, не нужно запускать несколько версий.

А как повесить разные фильтры на разные каналы?

Можно ли при конфигурации SkipWithKeywordsFilter через одну строку задать несколько слов для фильтрации?

Спасибо

**Comment by khoben** [comment]
> > Теперь фильтры прикручиваются к связке источник-целевой канал, не нужно запускать несколько версий.
> 
> А как повесить разные фильтры на разные каналы?
> 
> Можно ли при конфигурации SkipWithKeywordsFilter через одну строку задать несколько слов для фильтрации?
> 
> Спасибо

Для каждого направления можно задать свои фильтры:
```yaml
directions:
  - from: [-1001, -1002, -1003]
    to: [-100203]
    filters:
      - AllowWithKeywordsFilter:
          keywords: !!set
            ? "allowword1"
            ? "allowword12"
          lookup_whole_word: false
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? "stopword1"
          lookup_whole_word: false

  - from: [-1000#3] # forwards from topic to topic
    to: [-1001#4]
    filters:
      - AllowWithKeywordsFilter:
          keywords: !!set
            ? "allowword2"
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? "stopword2"
          lookup_whole_word: true
          

  - from: [-100226]
    to: [-1006, -1008]
    filters:
      - AllowWithKeywordsFilter:
          keywords: !!set
            ? "allowword2"
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? "stopword3"
          lookup_whole_word: true
```
Добавил фильтр `AllowWithKeywordsFilter`, который как раз будет пересылать только те сообщения, в которых встретяться нужны слова. И `lookup_whole_word` параметр, который если установить в `false` будет производить "нечеткий" поиск.
