### ISSUE TITLE
Not Forwarding Specific channel

### ISSUE THREAD

**Issue by physk** [khoben/telemirror#112]
is there any reason that a specific channel is not being mirrored?

```
 - from: [-1001479163323]
    to: [] # my channel id
    disable_delete: true
    filters:
      - ForwardFormatFilter:
          format: "Forwarded from [{channel_name}]({message_link})\n\n{message_text}"
```
          
I have other channels in my config that all seem to be working apart from this one.

it also doesn't receive the "New message" log in the log file when a message is receive on the channel

the bot is obviously a member of both channels
