### ISSUE TITLE
Message Filters aren't working

### ISSUE THREAD

**Issue by Fnc-Rishu** [khoben/telemirror#145]
![image](https://github.com/user-attachments/assets/c51fa491-e94d-4c20-bbcf-8226c0228425)
![image](https://github.com/user-attachments/assets/02d04e49-5c6c-4d21-bac1-e3a43e98846c)

**Comment by Fnc-Rishu** [comment]
Made the filters global for all and it worked

**Comment by khoben** [comment]
> Made the filters global for all and it worked

It should be worked not only for global filters. Check that the correct channel IDs are used.

**Comment by khoben** [comment]
> ![image](https://github.com/user-attachments/assets/c51fa491-e94d-4c20-bbcf-8226c0228425)
> ![image](https://github.com/user-attachments/assets/02d04e49-5c6c-4d21-bac1-e3a43e98846c)
> 

From your screenshot, the message came to the channel with ID 175..., but the filters are set to the channel with ID 188...

**Comment by Fnc-Rishu** [comment]
so we can set different filters for different channels ?

**Comment by khoben** [comment]
> so we can set different filters for different channels ?

Sure. For each "direction" item you set any group of filters.

Example `mirror.config.yml`:

```yaml
directions:
  - from: [-1002]
    to: [-1003]
    filters:
      - KeywordReplaceFilter:
          keywords:
            "one": "two"
            "good": "bad"
      - ForwardFormatFilter:
          format: "{sender_title} {sender_username} says:\n\n{message_text}"

  - from: [-1004]
    to: [-1005]
    filters:
      - UrlMessageFilter:
          blacklist: !!set
            ? t.me
            ? google.com
          placeholder: "REDACTED"
```
