### ISSUE TITLE
example to SkipWithKeywordsFilter

### ISSUE THREAD

**Issue by mthsfurio** [khoben/telemirror#60]
where i put keywords ?

`class SkipWithKeywordsFilter(MessageFilter):
    """Skips message if some keyword found
    """
    def __init__(self, keywords: set[str]) -> None:
        self._regex = re.compile(
            '|'.join([f'\\b{k}\\b' for k in keywords]), flags=re.IGNORECASE)

    async def process(self, message: EventMessage) -> Tuple[bool, EventMessage]:
        if self._regex.search(message.message):
            return False, message
        return True, message`

**Comment by khoben** [comment]
@mthsfurio 
Use `.env` to store API_ID, API_HASH and other credentials, and `mirror.config.yml` to configure filters and directions:
```yaml
# (Required) Mirror directions
directions:
  - from: [-1001, -1002, -1003]
    to: [-100203]

  - from: [-100226]
    to: [-1006, -1008]

# (Optional) Targets config
targets:
  - id: -1001
    filters:
      # Filter name with constructor parameters from telemirror.messagefilters module
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? cat
            ? dog
```

**Comment by mthsfurio** [comment]
now work bro =/ 
even though I put the words in the same format as you did, the messages are still being sent

**Comment by mthsfurio** [comment]
mirror.config.yml: 

```
# (Required) Mirror directions
directions:
  - from: [channel1]
    to: [channel2]


# (Optional) Targets config
targets:
  - id: channel1
    filters:
      # Filter name with constructor parameters from telemirror.messagefilters module
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? word1
            ? word2
            ? word3
```
if channel1 contains a message with word1, word2 or word3, it is still arriving on channel2
