### ISSUE TITLE
[FEATURE] Replace word - text transformation

### ISSUE THREAD

**Issue by lucag74** [khoben/telemirror#64]
I see in past someone ask this feature.
I'm a newbie on python so i'm not skilled to modify your code.

Usefull feature it's to replace some Word , or Phrase with another one.
**Real Scenario :** 

For example i have an Expert Advisort in MT4 that read signal from telegram, using of course a Telegram BOT, so the bot must be the administrator of channel.

I need to mirror original channel on my channel (where i put the bot), and this is working fine and it's amazing.
Original channel it's a signal channel, free or payment and i have no influence on the format or text.

However my expert advisor (of couse i don't have source to modify this one) maybe read only **TP** and not **TakeProfit**, so when i copy to my channel i need to transform .
In the original Message he write "TakeProfit" i need to transform in "**TP**", or maybe write "**trail stop loss to be**" i need to transform to "Set SL"

**Comment by khoben** [comment]
@lucag74 Keywords replacing feature is already here.
You should create `mirror.config.yml` file to work with it (see the last paragraph of 4th item of https://github.com/khoben/telemirror#prepare):
```yaml
directions:
  - from: [-1001]
    to: [-1002]

targets:
  - id: -1002
    filters:
      - KeywordReplaceFilter:
          keywords: 
            "TakeProfit": "TP"
            "trail stop loss to be": "Set SL"
```
