### ISSUE TITLE
where to find mirror.config.yml

### ISSUE THREAD

**Issue by iamysfy** [khoben/telemirror#76]
everything is fine but it seems that i can't find mirror.config.yml where to find it?
and if i have to make it how to exactly?

thanks for your great work and keep up the good work <3

**Comment by khoben** [comment]
`mirror.config.yml` file needs to be created by yourself. Here is an example:
```yaml
# (Optional) Global filters, will be applied in order
filters:
  - ForwardFormatFilter: # Filter name under telemirror/messagefilters.py
      format: ""           # Filters arguments
  - EmptyMessageFilter
  - UrlMessageFilter:
      blacklist: !!set
        ? t.me
  - SkipUrlFilter:
      skip_mention: false

# (Optional) Global settings
disable_edit: true
disable_delete: true

# (Required) Mirror directions
directions:
  - from: [-1001, -1002, -1003]
    to: [-100203]

  - from: [-100226]
    to: [-1006, -1008]
    # Overwrite global settings
    disable_edit: false
    disable_delete: false
    # Overwrite global filters
    filters:
      - UrlMessageFilter:
          blacklist: !!set
            ? t.me
```
